### ISSUE TITLE
Map quantitative values on the 3D model

### ISSUE THREAD

**Issue by ghost** [data-fun/3d-genome-builder#7]
I was following the steps in the tutorial to map quantitative values on the model run:

python ./scripts/map_parameter.py --pdb path/to/structure.pdb --bedgraph path/to/annotation.bedgraph --output path/to/output.pdb

The resultion is the same : 5kb 
The bedgraph :
chr1   0         606    116.959
chr1   606     614    48.4495
chr1   614     976    116.959
chr2   0         19      22.8726
chr3   0         2        22.8726
chr4   0        18       22.8726

I received the following error :

Number of beads read from structure: 1015
Traceback (most recent call last):
  File "/home/3d-genome-builder/./scripts/map_parameter.py", line 109, in <module>
    map_parameter(ARGS.pdb, ARGS.bedgraph, ARGS.output)
  File "/home/3d-genome-builder/./scripts/map_parameter.py", line 82, in map_parameter
    quantitative_parameter.columns = ["chromosome", "start", "end", "value"]
  File "/home/miniconda3/envs/3DGB/lib/python3.10/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/miniconda3/envs/3DGB/lib/python3.10/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/miniconda3/envs/3DGB/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/miniconda3/envs/3DGB/lib/python3.10/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 1 elements, new values have 4 elements

**Comment by pierrepo** [comment]
Hello @gayahaber 
Given the error message you had, I suspect your bedgraph file has space-separated values instead of tab-separated values.
Could you please verify this point?

**Comment by gayahaber** [comment]
Hello @pierrepo, 

No, my bedgraph is using a tab-seperated values. I writed again the bedgraph but still have the same error.
